export const PLAY_COPY = {
  title: "Error Garden",
  subtitle: "Pull the weeds, one tricky trap at a time.",
  focusTitle: "Focus filter",
  focusHint: "Change tags to scope the session. The URL always reflects focus.",
  matchLabel: "Match",
  matchAny: "Any tag",
  matchAll: "All tags",
  tagsLabel: "Tags",
  tagsAll: "All",
  progressLabel: "Progress",
  questionLabel: "Question",
  requiredLabel: "Required answers",
  selectedLabel: "Your answers",
  selectedCountLabel: "Selected",
  selectPrompt: "Select an option to continue.",
  nextQuestion: "Next question",
  finishSession: "Finish session",
  resultCorrect: "Correct",
  resultIncorrect: "Not yet",
  explanationLabel: "Explanation",
  correctAnswersLabel: "Correct answers",
  sessionCompleteTitle: "Session complete",
  sessionCompleteBody: "You reached the end of this focus.",
  startOver: "Start over",
  emptyStateTitle: "No questions match this filter.",
  emptyStateBody: "Try removing tags or switching match mode.",
} as const;
